name: agrisense
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  flare_flutter: ^3.0.2
  video_player: ^2.5.3
  youtube_player_flutter: ^8.0.0
  path_provider: ^2.0.13
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
  - assets/images/logologo.png
  - assets/images/userProf.png
  - assets/images/bgImage1.jpg
  - assets/videos/vid1.mp4
  - assets/images/Rice.png
  - assets/images/Maize.png
  - assets/images/Jute.png
  - assets/images/Cotton.png
  - assets/images/Coconut.png
  - assets/images/Papaya.png
  - assets/images/Orange.png
  - assets/images/Apple.png
  - assets/images/Muskmelon.png
  - assets/images/Watermelon.png
  - assets/images/Grapes.png
  - assets/images/Mango.png
  - assets/images/Banana.png
  - assets/images/Pomegranate.png
  - assets/images/Lentil.png
  - assets/images/Blackgram.png
  - assets/images/Mungbean.png
  - assets/images/Mothbeans.png
  - assets/images/Pigeonpeas.png
  - assets/images/Kidneybeans.png
  - assets/images/Chickpea.png
  - assets/images/Coffee.png
   
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
