class CropStat {
  static Map<String, Map<String, String>> cropStats = {
    "Rice": {
      "germination_rate": "7-14 days",
      "sunlight_required": "Full sun",
      "water_required": "High (flooded fields)",
      "growth_period": "90-150 days",
      "yield": "Varies",
      "companion_plants": "Azolla & Water spinach",
      "wind_tolerance": "Low",
      "max_height": "Varies",
      "propagation": "Seeds",
      "soil_type": "Well-drained loamy soil"
    },
    "Maize": {
      "germination_rate": "7-10 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "60-100 days",
      "yield": "Varies",
      "companion_plants": "Beans & Cucumber",
      "wind_tolerance": "Moderate",
      "max_height": "6-10 feet",
      "propagation": "Seeds",
      "soil_type": "Well-drained sandy loam"
    },
    "Jute": {
      "germination_rate": "10-20 days",
      "sunlight_required": "Full sun",
      "water_required": "High",
      "growth_period": "90-120 days",
      "yield": "Varies",
      "companion_plants": "Okra & Sunflower",
      "wind_tolerance": "Moderate",
      "max_height": "8-12 feet",
      "propagation": "Seeds",
      "soil_type": "Well-drained sandy soil"
    },
    "Cotton": {
      "germination_rate": "7-14 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "120-180 days",
      "yield": "Varies",
      "companion_plants": "Bean & Marigold",
      "wind_tolerance": "Moderate",
      "max_height": "3-6 feet",
      "propagation": "Seeds",
      "soil_type": "Well-drained loamy soil"
    },
    "Coconut": {
      "germination_rate": "2-3 months",
      "sunlight_required": "Full sun",
      "water_required": "High",
      "growth_period": "5-10 years",
      "yield": "100-200 coconuts/tree",
      "companion_plants": "Banana & Pineapple",
      "wind_tolerance": "High",
      "max_height": "30-100 feet",
      "propagation": "Seedlings",
      "soil_type": "Well-drained sandy soil"
    },
    "Papaya": {
      "germination_rate": "10-14 days",
      "sunlight_required": "Full sun",
      "water_required": "High",
      "growth_period": "180-330 days",
      "yield": "Varies",
      "companion_plants": "Basil & Nasturtium",
      "wind_tolerance": "Low",
      "max_height": "10-12 feet",
      "propagation": "Seeds",
      "soil_type": "Well-drained loamy soil"
    },
    "Orange": {
      "germination_rate": "10-14 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "365-730 days",
      "yield": "Varies",
      "companion_plants": "Chives & Marigold",
      "wind_tolerance": "Moderate",
      "max_height": "10-20 feet",
      "propagation": "Seeds",
      "soil_type": "Well-drained loamy soil"
    },
    "Apple": {
      "germination_rate": "14-30 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "365-1825 days",
      "yield": "Varies",
      "companion_plants": "Chamomile & Dill",
      "wind_tolerance": "Moderate",
      "max_height": "10-30 feet",
      "propagation": "Grafted trees",
      "soil_type": "Well-drained loamy soil"
    },
    "Muskmelon": {
      "germination_rate": "4-10 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "75-100 days",
      "yield": "Varies",
      "companion_plants": "Corn & Nasturtium",
      "wind_tolerance": "Low",
      "max_height": "Varies",
      "propagation": "Seeds",
      "soil_type": "Well-drained sandy loam"
    },
    "Watermelon": {
      "germination_rate": "4-10 days",
      "sunlight_required": "Full sun",
      "water_required": "High",
      "growth_period": "70-100 days",
      "yield": "Varies",
      "companion_plants": "Radish & Marigold",
      "wind_tolerance": "Low",
      "max_height": "Varies",
      "propagation": "Seeds",
      "soil_type": "Well-drained sandy loam"
    },
    "Grapes": {
      "germination_rate": "10-20 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "365-730 days",
      "yield": "Varies",
      "companion_plants": "Rosemary & Tansy",
      "wind_tolerance": "Moderate",
      "max_height": "Varies",
      "propagation": "Cuttings",
      "soil_type": "Well-drained loamy soil"
    },
    "Mango": {
      "germination_rate": "10-14 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "180-365 days",
      "yield": "Varies",
      "companion_plants": "Basil & Marigold",
      "wind_tolerance": "Moderate",
      "max_height": "30-100 feet",
      "propagation": "Grafted trees",
      "soil_type": "Well-drained loamy soil"
    },
    "Banana": {
      "germination_rate": "10-20 days",
      "sunlight_required": "Full sun",
      "water_required": "High",
      "growth_period": "365-730 days",
      "yield": "Varies",
      "companion_plants": "Beans & Cabbage",
      "wind_tolerance": "Low",
      "max_height": "6-25 feet",
      "propagation": "Rhizomes",
      "soil_type": "Well-drained sandy loam"
    },
    "Pomegranate": {
      "germination_rate": "14-30 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "365-730 days",
      "yield": "Varies",
      "companion_plants": "Basil & Marigold",
      "wind_tolerance": "Moderate",
      "max_height": "10-20 feet",
      "propagation": "Seeds",
      "soil_type": "Well-drained sandy loam"
    },
    "Lentil": {
      "germination_rate": "7-14 days",
      "sunlight_required": "Full sun",
      "water_required": "Low to moderate",
      "growth_period": "90-120 days",
      "yield": "Varies",
      "companion_plants": "Carrot & Chickpea",
      "wind_tolerance": "Low",
      "max_height": "Varies",
      "propagation": "Seeds",
      "soil_type": "Well-drained sandy loam"
    },
    "Blackgram": {
      "germination_rate": "7-14 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "90-120 days",
      "yield": "Varies",
      "companion_plants": "Sesame & Mungbean",
      "wind_tolerance": "Moderate",
      "max_height": "Varies",
      "propagation": "Seeds",
      "soil_type": "Well-drained sandy loam"
    },
    "Mungbean": {
      "germination_rate": "4-7 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "60-90 days",
      "yield": "Varies",
      "companion_plants": "Maize & Cucumber",
      "wind_tolerance": "Low",
      "max_height": "Varies",
      "propagation": "Seeds",
      "soil_type": "Well-drained sandy loam"
    },
    "Mothbeans": {
      "germination_rate": "4-7 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "60-90 days",
      "yield": "Varies",
      "companion_plants": "Cucumber & Radish",
      "wind_tolerance": "Low",
      "max_height": "Varies",
      "propagation": "Seeds",
      "soil_type": "Well-drained sandy loam"
    },
    "Pigeonpeas": {
      "germination_rate": "7-14 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "180-365 days",
      "yield": "Varies",
      "companion_plants": "Maize & Sorghum",
      "wind_tolerance": "Moderate",
      "max_height": "6-10 feet",
      "propagation": "Seeds",
      "soil_type": "Well-drained loamy soil"
    },
    "Kidneybeans": {
      "germination_rate": "7-14 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "90-150 days",
      "yield": "Varies",
      "companion_plants": "Corn & Potato",
      "wind_tolerance": "Moderate",
      "max_height": "Varies",
      "propagation": "Seeds",
      "soil_type": "Well-drained loamy soil"
    },
    "Chickpea": {
      "germination_rate": "7-14 days",
      "sunlight_required": "Full sun",
      "water_required": "Moderate",
      "growth_period": "90-120 days",
      "yield": "Varies",
      "companion_plants": "Tomato & Cilantro",
      "wind_tolerance": "Moderate",
      "max_height": "Varies",
      "propagation": "Seeds",
      "soil_type": "Well-drained loamy soil"
    },
    "Coffee": {
      "germination_rate": "30-60 days",
      "sunlight_required": "Partial shade",
      "water_required": "Moderate",
      "growth_period": "365-730 days",
      "yield": "Varies",
      "companion_plants": "Nasturtium & Lemon balm",
      "wind_tolerance": "Low",
      "max_height": "3-8 feet",
      "propagation": "Seeds or cuttings",
      "soil_type": "Well-drained loamy soil"
    },
  };

  static Map<String, String> cropNameSeason = {
    'Rice': 'Wet Season',
    'Maize': 'Dry Season & Wet Season',
    'Jute': 'Wet Season',
    'Cotton': 'Dry Season',
    'Coconut': 'Wet Season',
    'Papaya': 'Wet Season',
    'Orange': 'Wet Season',
    'Apple': 'Wet Season',
    'Muskmelon': 'Dry Season',
    'Watermelon': 'Wet Season',
    'Grapes': 'Dry Season & Wet Season',
    'Mango': 'Dry Season & Wet Season',
    'Banana': 'Wet Season',
    'Pomegranate': 'Dry Season & Wet Season',
    'Lentil': 'Dry Season',
    'Blackgram': 'Dry Season',
    'Mungbean': 'Dry Season',
    'Mothbeans': 'Dry Season',
    'Pigeonpeas': 'Dry Season & Wet Season',
    'Kidneybeans': 'Dry Season',
    'Chickpea': 'Dry Season',
    'Coffee': 'Wet Season',
  };
}
