class GenusDataClass {
  static Map<String, String> cropGenusMap = {
    'Apple': 'Malus',
    'Banana': 'Musa',
    'Blackgram': 'Vigna',
    'Chickpea': 'Cicer',
    'Coffee': 'Coffea',
    'Coconut': 'Cocos',
    'Cotton': 'Gossypium',
    'Grapes': 'Vitis',
    'Jute': 'Corchorus',
    'Kidneybeans': 'Phaseolus',
    'Lentil': 'Lens',
    'Maize': 'Zea',
    'Mango': 'Mangifera',
    'Mothbeans': 'Vigna',
    'Mungbean': 'Vigna',
    'Muskmelon': 'Cucumis',
    'Orange': 'Citrus',
    'Papaya': 'Carica',
    'Pigeonpeas': 'Cajanus',
    'Pomegranate': 'Punica',
    'Rice': 'Oryza',
    'Watermelon': 'Citrullus',
  };
}
